services:
  totp-generator:
    container_name: totp-generator
    image: totp-generator:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    restart: on-failure
    network_mode: host
