import express, { Application, Express, NextFunction, Request, Response } from "express";
import { subController } from "./components/sub/sub-controller.js";

const createApp = (): Application => {
 
  const app: Express = express();

  // Configure body-parser
  app.use(express.json());
  app.use(express.urlencoded({ extended: true }));


  app.get("/sub-generator", (req: Request, res: Response, next: NextFunction) => 
    subController(req, res)
  );

  app.get('/', (req: Request, res: Response) => {
    res.send(`
      <h1>sub(ject identifier) generator </h1>
      <p>Generate a sub that looks like one generated by GOV.UK One Login by making a GET request to: <code>/sub-generator?id={your-id}&amp;sector={your-sector}</code></p>
      <p>Example: <a href="./sub-generator?id=1234567890&amp;sector=https%3A%2F%2Fsomething.gov.uk">./sub-generator?id=1234567890&amp;sector=https%3A%2F%2Fsomething.gov.uk</a></p>
    `);
  });

  return app;
};

export { createApp };