services:
  f2f-test:
    container_name: f2f-test
    image: f2f-test:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    restart: on-failure
    network_mode: host